language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t balazsprehoda/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true balazsprehoda/docker-react npm run test
